blank_issues_enabled: false
contact_links:
  - name: Discord - PT-BR
    url: https://discord.gg/ttGU4QKn6A
    about: Por favor, pergunte e responda a perguntas aqui.
  - name: Discord - EN-US
    url: https://discord.gg/2nA2GPtJYc
    about: Please ask and answer questions here.
